### ISSUE TITLE
Rework dir struct of apps into examples/ & tests (tests is echo + api)

### ISSUE THREAD

**Issue by galak** [OpenAMP/open-amp#101]
Make a cleaner split between examples and tests.  So lets re-org the apps dir as follows:

apps/tests/
apps/examples/
apps/platform/

apps/echo_test/ & apps/echo_test_decouple -> apps/examples/echo
apps/func_test_suite -> apps/tests/api
apps/linux_firmware_remoteproc_slave -> apps/platform ???
apps/load_fw -> apps/platform ???
apps/machine -> apps/platform
apps/matrix_multiply -> apps/examples/matrix_multiply
apps/rpc_demo -> apps/examples/rpc_demo
apps/systerm -> apps/platform

**Comment by wjliang** [comment]
merged to master-decouple-staging
