### ISSUE TITLE
Add 'slave' app to match Linux Kernel samples/rpmsg/rpmsg_client_sample.c

### ISSUE THREAD

**Issue by galak** [OpenAMP/open-amp#102]
Create a 'slave' app as part of open-amp apps/examples/ that implements the slave side communication to the Linux Kernel sample samples/rpmsg/rpmsg_client_sample.c

**Comment by wjliang** [comment]
merged to master-decouple-staging

**Comment by wjliang** [comment]
will need to merge to the master-decouple-staging
