### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by dtrussel** [OpenAMP/open-amp#172]
Looks like this document is quite old and describes a different API.
https://github.com/OpenAMP/open-amp/blob/master/docs/openamp_ref.pdf

**Comment by wjliang** [comment]
The document has been removed by pull request: https://github.com/OpenAMP/open-amp/pull/174

**Comment by ChrisYin** [comment]
README files in docs/apps are also out-dated.
```
obsolete/apps/echo_test/system/linux/kernelspace/rpmsg_user_dev_driver  if you want to run the echo_test app in Linux user space.
obsolete/system/linux/kernelspace/rpmsg_echo_test_kern_app  if you want to run the echo_test app in Linux kernel space.

```
There is no obsolete directory in the current version.

**Comment by arnopo** [comment]
https://openamp.readthedocs.io/en/latest/ should answer to this issue
