### ISSUE TITLE
C++ compatibility errors

### ISSUE THREAD

**Issue by mizmar** [OpenAMP/open-amp#178]
Nested structs and unions have different visibility rules in C and C++ and causes compilation error from defined here:

https://github.com/OpenAMP/open-amp/blob/e558ab30f521edd15e7c5361768df09e9267cf97/lib/include/openamp/virtqueue.h#L96-L99

and used here:

https://github.com/OpenAMP/open-amp/blob/e558ab30f521edd15e7c5361768df09e9267cf97/lib/include/openamp/virtqueue.h#L204

minimal example of the issue: https://godbolt.org/z/7GElZ4

Solution could be either to move definition of `struct vq_desc_extra` outside of `struct virtqueue`, or make function `virtqueue_allocate()` not inline, but rather implemented in C source file.

Such issues can be identified with `-Wc++-compat` flag on GCC, but are only relevant for header files included into C++ source files.

**Comment by arnop2** [comment]
@mizmar 
IMHO Moving vq_desc_extra  struct definition out of struct virtqueue is simple and smart.
Is it possible to test it in your C++ env and send a pull request with the fix?
Thanks!
