### ISSUE TITLE
Can multiple rpmsg_rtos_alloc_tx_buffer() calls be made prior to rpmsg_rtos_send_nocopy()?

### ISSUE THREAD

**Issue by jmcclin2** [OpenAMP/open-amp#181]
We are currently experiencing a bug on the iMX7s using rpmsg where the M-core is getting the SAME buffer from rpmsg_rtos_alloc_tx_buffer() before it is ever en-queued during rpmsg_rtos_send_nocopy().  A-core is running Linux and is the MASTER, M-core is running MQX. 
 We see the M-core get the same buffer 4 times in row, and as a result the data is corrupted when received on the A-core.  The bug has a low encounter rate, but is easy to re-produce when we generate a lot of transmissions from the M-core to the A-core.  It may be that this is not a bug but that we are misusing rpmsg_rtos_alloc_tx_buffer() ?  

Is it required that you complete a call to rpmsg_rtos_send_nocopy() before you call rpmsg_rtos_alloc_tx_buffer() again?  The underlying code for rpmsg_rtos_alloc_tx_buffer() led us to believe that is simply gets the next available packet, but maybe that is not the case?

thanks,
Jeremy

**Comment by arnopo** [comment]
@jmcclin2 
Apologies,  your question never received an answer...
You faced an issue probably because the rpmsg_rtos layer is not part of the OpenAMP, so would need to be re-adapt to the OpenAMP. I would suggest to contact NXP for support if not already done.
