### ISSUE TITLE
OpenAMP on x86

### ISSUE THREAD

**Issue by XYEFA** [OpenAMP/open-amp#183]
All of the OpenAMP examples I have seen are ARM specific. Is OpenAMP supported on x86 (Linux + RTOS)?

**Comment by xiaoxiang781216** [comment]
We test OpenAMP between two RTOS which run on Ubuntu as a hybrid simulator:
https://bitbucket.org/nuttx/nuttx/src/master/boards/sim/sim/sim/README.txt:rpserver section
Here is info about how the simulator work:
https://nuttx.org/doku.php?id=wiki:nxinternal:simulator

**Comment by XYEFA** [comment]
Thank you for the answer - Do you have to rebuild Ubuntu or is OpenAMP or remoteproc included natively?

**Comment by xiaoxiang781216** [comment]
> Thank you for the answer - Do you have to rebuild Ubuntu or is OpenAMP or remoteproc included natively?

No, but OpenAMP officially support two native instance(process) talk each other in Ubuntu.
