### ISSUE TITLE
Update cmake_minimum_required() from 2.6 to something more recent

### ISSUE THREAD

**Issue by edmooring** [OpenAMP/open-amp#214]
We currently have cmake_minimum_required(VERSION 2.6) in our CMakeLists.txt. 

We should probably upgrade to a newer minimum, as version 2.6 has probably not been tested in a long time.

**Comment by arnopo** [comment]
For ST platform we use at minimum cmake 3.5
Zephyr use version higher than 3.13

**Comment by arnopo** [comment]
Suggestion from @tejlmand to migrate to use cmake 3.0.2 as minimum supported  version:
https://github.com/OpenAMP/open-amp/pull/213#issuecomment-651753117

**Comment by edmooring** [comment]
That seems like a good idea.
