### ISSUE TITLE
apps: platform_release_rpmsg_vdev not implemented

### ISSUE THREAD

**Issue by arnopo** [OpenAMP/open-amp#231]
platform_release_rpmsg_vdev fonction is void in applications. Need to free resources (e.g virtio) allocated in platform_create_rpmsg_vdev.

List of files potentially concerned:
apps/system/linux/machine/generic/platform_info.c
apps/system/linux/machine/generic/platform_info.h
apps/machine/zynq7/platform_info.c
apps/machine/zynq7/platform_info.h
apps/machine/zynqmp_r5/platform_info.c
apps/machine/zynqmp_r5/platform_info.h
apps/machine/zynqmp/platform_info.c
apps/machine/zynqmp/platform_info.h

**Comment by bentheredonethat** [comment]
working on branch for this now
