### ISSUE TITLE
Copyright and license in apps/examples

### ISSUE THREAD

**Issue by takayuki-imada** [OpenAMP/open-amp#235]
Could you please add copyright and license information to source files in apps/examples/{echo,matrix_multiply,rpc_demo,rpmsg_sample_echo}/ ?

The source files don't have any information about them.

Thanks,

**Comment by arnopo** [comment]
@takayuki-imada 
Thanks for the information!  Is the copyright also an issue for you or only the licensing?
Feel free to propose a fix to accelerate the correction.

**Comment by takayuki-imada** [comment]
@arnopo 
Licensing is my concern.
I just want to know what kind of license is applied to the source files I pointed out.
BSD-3(or2)-Clause as shown in LICENSE.md, or another?

**Comment by arnopo** [comment]
Yes  as mentioned in https://github.com/OpenAMP/open-amp/blob/master/LICENSE.md, you can use the BSD-3-Clause

**Comment by takayuki-imada** [comment]
Thanks, that's good enough information to me!

**Comment by arnopo** [comment]
Reopen as we need to fix it for next release

**Comment by arnopo** [comment]
issue addressed by https://github.com/OpenAMP/open-amp/pull/245
