### ISSUE TITLE
Update CMake Infrastructure

### ISSUE THREAD

**Issue by edmooring** [OpenAMP/open-amp#243]
Our CMake infrastructure hasn't changed since it was committed. CMake itself has evolved quite a bit since then. There may be improvements we can make.

**Comment by arnopo** [comment]
Hi @Ed,
could we close this issue or could you details what you have in mind

**Comment by edmooring** [comment]
I think we can close this, as it is very vague. We have cleaned up some CMake warnings to bring parts of the infrastructure up to date.
