### ISSUE TITLE
compilation error for microblaze platform

### ISSUE THREAD

**Issue by georgiy-pruss** [OpenAMP/open-amp#252]
open-amp/apps/machine/microblaze_generic/platform_info.c 

platform_release_rpmsg_vdev - two definitions on line 196 and 208.

lines 210 211 - parentheses not balanced and it looks not finished.

Thank you!

**Comment by arnopo** [comment]
Hi @georgiy-pruss 

Thanks for the report!
seems that platform_release_rpmsg_vdev is twice defined...and the second one has to be removed
could you send a PR to fix?
