### ISSUE TITLE
elf_loader is not compatible with C++ executable

### ISSUE THREAD

**Issue by alexian79** [OpenAMP/open-amp#27]
Hi I am not sure but following code in elf_loader_load_sections prevents loading C++ constructor initialization section
			/* Check if the section is part of runtime and is not section with
			 * no-load attributes such as BSS or heap. */
			if ((current->sh_type & SHT_NOBITS) == 0) {

sh_type for that kind of sections is #define     SHT_INIT_ARRAY          14
and #define     SHT_FINI_ARRAY          15
which is 0xE or 0xF in hex
BR, Alex.

**Comment by wjliang** [comment]
Do you mean C++ constructor initialization section will have SHT_NOBITS (that is no data) ?

Thanks,
Wendy

**Comment by alexian79** [comment]
yes exactly

**Comment by wjliang** [comment]
I am thinking to use load loadable segment instead of check the details of each section.

**Comment by wjliang** [comment]
please check this issue https://github.com/OpenAMP/open-amp/issues/40 for the change of remoteproc to load a firmware, will load segments instead of sections, will it work for your case?

**Comment by wjliang** [comment]
This issue should be solved in the latest OpenAMP code.
