### ISSUE TITLE
RPC demo quesiton:  Only one task in freeRTOS can do IO redirection? Or I can have mutli task do IO rediction?

### ISSUE THREAD

**Issue by WinnieeBear** [OpenAMP/open-amp#308]
Hi,

I have a xilinx zu5 develop board, coreA53 runs linux, and coreR0 runs freeRTOS.
I have successfully run the RPC demo which one task in freeRTOS do the IO redirection using the rpmsg with linux.
Now, I have a qustion. Can i have more than one task do the IO redirection with linux? I try to create another task but it seems can't do the IO redirection. Could you help to confirm?

Thanks,
Sean

**Comment by arnopo** [comment]
Hello @WinnieeBear 

Thanks for the context.
Seems that you are are blocked in the "processing" task. In libmetal the mutex is not well impemented for the FreeRTOS system.
Could you apply following libmetal fix and retry?
https://github.com/OpenAMP/libmetal/pull/148.
To get the patch associated to the PR: `wget https://github.com/OpenAMP/libmetal/pull/148.patch `

**Comment by WinnieeBear** [comment]
> Hello @WinnieeBear
> 
> Thanks for the context. Seems that you are are blocked in the "processing" task. In libmetal the mutex is not well impemented for the FreeRTOS system. Could you apply following libmetal fix and retry? [OpenAMP/libmetal#148](https://github.com/OpenAMP/libmetal/pull/148). To get the patch associated to the PR: `wget https://github.com/OpenAMP/libmetal/pull/148.patch `

Hi @arnopo 

It seems it doesn't work too.

I have change the file mutex.h in libmetal it still fails to schedule.

Thanks,
Sean

**Comment by edmooring** [comment]
There is also an issue with FreeRTOS scheduling on the R5 that was fixed in the Xilinx OpenAMP release 2021.1 but has not been upstreamed. See https://github.com/Xilinx/embeddedsw/commit/310af6073a5670436c36475d00f000473a54b67a#diff-6854d96c5fd1e851a7029b0f2d7eafecd2b8ea2dac5e6a24fd9be2b1fba57985

**Comment by arnopo** [comment]
I close this issue, please reopen It if it is still valid
