### ISSUE TITLE
device tree example is broken

### ISSUE THREAD

**Issue by John-Ingersoll** [OpenAMP/open-amp#31]
https://github.com/OpenAMP/open-amp/blob/master/apps/machine/zynqmp/openamp-linux-userspace.dtsi  - the VRING, SHMEM and IPI nodes are missing a 0x0 entry in the register fields.

IS: reg = <0x0 0x3ed00000 0x10000>;
SHOULD BE: reg = <0x0 0x3ed00000 **0x0** 0x10000>;

**Comment by wjliang** [comment]
Thanks John, I have updated the example to line up with the latest Xilinx 2017.3 kernel.
