### ISSUE TITLE
openamp rpmsg in linux userspace    ERROR: failed to open shm device: -2.

### ISSUE THREAD

**Issue by wangyong5123** [OpenAMP/open-amp#310]
Xilinx Zynq MP First Stage Boot Loader 
Release 2020.2   Oct 20 2021  -  06:25:23
PMU Firmware 2020.2     Oct 20 2021   06:24:32
PMU_ROM Version: xpbr-v8.1.0-0
Starting application...
                       Initialize remoteproc successfully.
creating remoteproc virtio
NOTICE:  ATF running on XCZU3EG/silicon v4/RTL5.1 at 0xfffea000
NOTICE:  BL31: v2.2(release):xlnx_rebase_v2.2_2020.3
NOTICE:  BL31: Built : 02:54:00, Oct 22 2021

U-Boot 2020.01 (Oct 22 2021 - 06:56:56 +0000)
Board: Xilinx ZynqMP
DRAM:  4 GiB
PMUFW:  v1.1
EL Level:       EL2
Chip ID:        zu3eg
NAND:  0 MiB
MMC:   mmc@ff160000: 0, mmc@ff170000: 1
In:    serial@ff000000
Out:   serial@ff000000
Err:   serial@ff000000
Bootmode: SD_MODE1
Reset reason:   EXTERNAL 
Hit any key to stop autoboot:  0 
switch to partitions #0, OK
mmc1 is current device
Scanning mmc 1:1...
Found U-Boot script /boot.scr
2007 bytes read in 16 ms (122.1 KiB/s)

system setup successful
#./rpmsg-echo
bus_name=platform,shm_name=3ed20000.shm
**ERROR: failed to open shm device: -2.
Failed to create remoteproc device.
ERROR: Failed to initialize platform.**

why failed to open shm?

shm info
root@ZYNQ:/sys/devices/platform/amba/3ed20000.shm# ls -l
total 0
-rw-r--r--    1 root     root          4096 Oct 22 07:03 driver_override
-r--r--r--    1 root     root          4096 Oct 22 07:05 modalias
lrwxrwxrwx    1 root     root             0 Oct 22 07:05 of_node -> ../../../../firmware/devicetree/base/amba/shm@0
drwxr-xr-x    2 root     root             0 Oct 22 07:05 power
lrwxrwxrwx    1 root     root             0 Oct 22 07:05 subsystem -> ../../../../bus/platform
-rw-r--r--    1 root     root          4096 Jan  1  1970 uevent

**Comment by arnopo** [comment]
Hello @wangyong5123 

The -2 error indicates that you are trying to open a shared memory that is not registered. 
It seems that the metal_shmem_register_generic call is missing or there is a mismatch between the name of the registered shared memory and the opened one.

**Comment by wangyong5123** [comment]
Hello @arnopo

**kernel drivers information  **
root@ZYNQ:/sys/devices/platform/amba/**3ed20000.shm**# ls -l
total 0
-rw-r--r-- 1 root root 4096 Oct 22 07:03 driver_override
-r--r--r-- 1 root root 4096 Oct 22 07:05 modalias
lrwxrwxrwx 1 root root 0 Oct 22 07:05 of_node -> ../../../../firmware/devicetree/base/amba/shm@0
drwxr-xr-x 2 root root 0 Oct 22 07:05 power
lrwxrwxrwx 1 root root 0 Oct 22 07:05 subsystem -> ../../../../bus/platform
-rw-r--r-- 1 root root 4096 Jan 1 1970 uevent

the system  have  already registered 3ed20000.shm




I got source code  and not modify it 
**platform_info.c**
#define RPU_CPU_ID          0 /* RPU remote CPU Index. We only talk to  
                               * one CPU in the exmaple. We set the CPU
                               * index to 0. */
#ifdef versal
#define IPI_CHN_BITMASK     0x08 /* IPI channel bit mask for IPI
					* from/to RPU0 */
#define IPI_DEV_NAME        "ff360000.ipi" /* IPI device name */
#else
#define IPI_CHN_BITMASK	    0x00000100
#define IPI_DEV_NAME	    "ff340000.ipi"
#endif /* versal */
#define DEV_BUS_NAME        "platform" /* device bus name. "platform" bus
                                        * is used in Linux kernel for generic
					* devices */
/* libmetal devices names used in the examples.
 * They are platform devices, you find them in Linux sysfs
 * sys/bus/platform/devices */
**#define SHM_DEV_NAME        **"3ed20000.shm" /* shared device name */****

#define RSC_MEM_PA          0x3ED20000UL
#define RSC_MEM_SIZE        0x2000UL
#define VRING_MEM_PA        0x3ED40000UL
#define VRING_MEM_SIZE      0x8000UL
#define SHARED_BUF_PA       0x3ED48000UL
#define SHARED_BUF_SIZE     0x40000UL

I get source code form github and not midify  
if  the metal_shmem_register_generic call is missing  how to solve it?

**Comment by arnopo** [comment]
@edmooring , @bentheredonethat,
Any advice?

**Comment by arnopo** [comment]
@wangyong5123 
can I close this issue ?

**Comment by TanmayShah-xilinx** [comment]
Please refer to: https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/2423717889/RPMsg+in+Linux+and+OpenAMP+Project#RPMsg-in-Userspace

@arnopo we can close the issue.
