### ISSUE TITLE
About notifyid in "handle_vdev_rsc" function

### ISSUE THREAD

**Issue by lozdznil** [OpenAMP/open-amp#314]
Hi,

I'm a little confused about the following code in `handle_vdev_rsc` function in `rsc_table_parser.c` (lib/remoteproc/):

```c
for (i = 0; i < num_vrings; i++) {
	struct fw_rsc_vdev_vring *vring_rsc;

	vring_rsc = &vdev_rsc->vring[i];
	notifyid = vring_rsc->notifyid;
	notifyid = remoteproc_allocate_id(rproc,
					  notifyid,
					  notifyid + 1);
	if (notifyid != RSC_NOTIFY_ID_ANY)
		vdev_rsc->notifyid = notifyid;
}
```

Here it uses `vring_rsc->notifyid` to allocate new IDs, but finally updates `vdev_rsc->notifyid` rather than `vring_rsc->notifyid`.

Is this a typo? My understanding is that it should be like this:

```diff
for (i = 0; i < num_vrings; i++) {
	struct fw_rsc_vdev_vring *vring_rsc;

	vring_rsc = &vdev_rsc->vring[i];
	notifyid = vring_rsc->notifyid;
	notifyid = remoteproc_allocate_id(rproc,
					  notifyid,
					  notifyid + 1);
	if (notifyid != RSC_NOTIFY_ID_ANY)
-		vdev_rsc->notifyid = notifyid;
+		vring_rsc->notifyid = notifyid;
}
```

Thanks!

**Comment by arnopo** [comment]
Hello @lozdznil 

Thanks for poiting out this!
Yes this seems not correct. Could you send a PR to propose a fix?
