### ISSUE TITLE
rproc_virtio_get_features does not need to read dfeatures

### ISSUE THREAD

**Issue by tammyleino** [OpenAMP/open-amp#346]
The rproc_virtio_get_features function reads both dfeatures and gfeatures from the vdev entry and returns bits set in both fields. It is not clear why this function reads dfeatures because gfeatures should already contain only those features which are set in dfeatures.

The description of these fields in remoteproc.h suggests that gfeatures should not provide more features than defined in dfeatures:

```
 * @dfeatures specifies the virtio device features supported by the firmware
 * @gfeatures is a place holder used by the host to write back the negotiated features that are supported by both sides.

```
It seems reading of dfeatures is not needed in the rproc_virtio_get_features function and can be removed.

**Comment by edmooring** [comment]
This looks correct to me. @dfeatures is what the device supports, @gfeatures is what features the two ends have negotiated. Clients do not need to see features that might not be there.

**Comment by tammyleino** [comment]
@edmooring then wouldn't just returning gfeatures be sufficient?  ANDing it with dfeatures doesn't return anything additional.

**Comment by edmooring** [comment]
> @edmooring then wouldn't just returning gfeatures be sufficient? ANDing it with dfeatures doesn't return anything additional.

That's what I think as well. It looks to me like the set_features() call does this ANDing already. @arnopo what do you think?

**Comment by arnopo** [comment]
This can be considered as a cross-check. Simplifying this means that we trust the remote side. I would be in favor of keeping it.

**Comment by edmooring** [comment]
> This can be considered as a cross-check. Simplifying this means that we trust the remote side. I would be in favor of keeping it.

I see your point. That brings up an interesting architectural issue: How much do we or can we trust the remote side, and how do we protect ourselves against it?

**Comment by arnopo** [comment]
I propose to close the issue an d keep current implementation

**Comment by edmooring** [comment]
@tammyleino @arnopo I agree with closing this issue.
