### ISSUE TITLE
rpmsg_virtio_get_buffer_size returns 0 in case of failure

### ISSUE THREAD

**Issue by tammyleino** [OpenAMP/open-amp#348]
rpmsg_virtio.h describes this routine as returning a negative value for failure:

```
/**
 * rpmsg_virtio_get_buffer_size - get rpmsg virtio buffer size
 *
 * @rdev - pointer to the rpmsg device
 *
 * @return - next available buffer size for text, negative value for failure
 */
int rpmsg_virtio_get_buffer_size(struct rpmsg_device *rdev);
```

But the routine actually returns 0.  Is the return value wrong, or is the comment in the header file wrong?

**Comment by rdev** [comment]
Pls wrap code snippets so random people don't get tagged 😬

**Comment by edmooring** [comment]
> rpmsg_virtio.h describes this routine as returning a negative value for failure:
> 
> ```
> /**
>  * rpmsg_virtio_get_buffer_size - get rpmsg virtio buffer size
>  *
>  * @rdev - pointer to the rpmsg device
>  *
>  * @return - next available buffer size for text, negative value for failure
>  */
> int rpmsg_virtio_get_buffer_size(struct rpmsg_device *rdev);
> ```
> 
> But the routine actually returns 0. Is the return value wrong, or is the comment in the header file wrong?

I think the comment in the header file is wrong. I don't see any way for this code to ever return anything other than 0 or a proper length.

**Comment by arnopo** [comment]
`rpmsg_virtio_get_buffer_size` can return [RPMSG_ERR_PARAM](https://github.com/OpenAMP/open-amp/blob/main/lib/rpmsg/rpmsg_virtio.c#L613)

**Comment by tammyleino** [comment]
@arnopo Can you please point out the condition(s) under which this could happen.  Perhaps I am reading the code wrong.

**Comment by edmooring** [comment]
> @arnopo Can you please point out the condition(s) under which this could happen. Perhaps I am reading the code wrong.

I'm not @arnopo, but here's the code:

```
int rpmsg_virtio_get_buffer_size(struct rpmsg_device *rdev)
{
        int size;
        struct rpmsg_virtio_device *rvdev;

        if (!rdev)
                return RPMSG_ERR_PARAM;
        metal_mutex_acquire(&rdev->lock);
        rvdev = (struct rpmsg_virtio_device *)rdev;
        size = _rpmsg_virtio_get_buffer_size(rvdev);
        metal_mutex_release(&rdev->lock);
        return size;
}
```
If rpmsg_virtio_get_buffer() is called with a NULL rdev, it will return a negative number. I had missed the subtle difference between _rpmsg_virtio_get_buffer_size() and rpmsg_virtio_get_buffer_size() which calls it.

**Comment by tammyleino** [comment]
@edmooring  @arnopo  The error I am referring to is when rpmsg_virtio_get_buffer_size calls _rpmsg_virtio_get_buffer_size and virtqueue_get_desc_size returns a negative value :

'''
		/*
		 * If other core is Master then buffers are provided by it,
		 * so get the buffer size from the virtqueue.
		 */
		length =
		    (int)virtqueue_get_desc_size(rvdev->svq) -
		    sizeof(struct rpmsg_hdr);
		**if (length < 0) {
			length = 0;**
		}
'''
Furthermore, I would say this check should be == 0 since virtqueue_get_desc_size returns a uint32_t and will return 0 when no buffers are available.

**Comment by arnopo** [comment]
Right, following code seems useless as virtqueue_get_desc_size return an uint32_t
```
if (length < 0) {
			length = 0;
```
