### ISSUE TITLE
Missing headers files in vitis 2021.1

### ISSUE THREAD

**Issue by jg-spitfire** [OpenAMP/open-amp#350]
Hi, I am following the UG1186 v2021.1 page 44 from Xilinx which declares that for running the rpmsg-echo test in the remote processor these source file are required:
https://github.com/OpenAMP/open-amp/blob/main/apps/examples/echo/rpmsg-echo.c
https://github.com/OpenAMP/open-amp/blob/main/apps/machine/zynqmp_r5/platform_info.c
https://github.com/OpenAMP/open-amp/blob/main/apps/machine/zynqmp_r5/platform_info.h
https://github.com/OpenAMP/open-amp/blob/main/apps/machine/zynqmp_r5/rsc_table.c
https://github.com/OpenAMP/open-amp/blob/main/apps/machine/zynqmp_r5/rsc_table.h

but once I create an app in the r50 processor and use all those sources I have a lot of errors in the compilation, Vitis says there are missing .h files, so what sources do I need to reproduce this test?

**Comment by jg-spitfire** [comment]
https://raw.githubusercontent.com/OpenAMP/open-amp/main/apps/examples/echo/rpmsg-echo.h is also included

**Comment by arnopo** [comment]
Hi @jg-spitfire,
Do you contact Xilinx Support? your issue seems related to the implementation on a Xilinx Platform

**Comment by edmooring** [comment]
The Xilinx fork of OpenAMP has diverged in a number of ways from upstream, and also lags upstream OpenAMP by a release or two. Mixing the library from Xilinx with the upstream apps may not always work.

**Comment by edmooring** [comment]
We should close this issue.
