### ISSUE TITLE
What is the purpose of the buf argument in get_mem function of remoteproc_ops structure?

### ISSUE THREAD

**Issue by arnopo** [OpenAMP/open-amp#352]
### Discussed in https://github.com/OpenAMP/open-amp/discussions/345

<div type='discussions-op-text'>

<sup>Originally posted by **tammyleino** February  4, 2022</sup>
The "get_mem" function in the remoteproc_ops structure has a "buf" argument. This argument is not documented in the input parameters. What is the purpose of "buf" argument in the "get_mem" function?</div>

**Comment by arnopo** [comment]
Right `Buf` argument need to be documented.
This API is related to https://github.com/OpenAMP/open-amp/pull/169 proposed by @xiaoxiang781216 
Inspired by https://en.cppreference.com/w/c/chrono/gmtime

proposal:
```
	 * get_mem
	 *
	 * get remoteproc memory I/O region by either name, virtual
	 * address, physical address or device address.
	 *
	 * @rproc - pointer to remoteproc instance
	 * @name - memory name
	 * @pa - physical address
	 * @da - device address
	 * @va - virtual address
	 * @size - memory size
+	 * @buf - pointer to a local remoteproc_mem struct object to store the result
	 *
	 * @returns remoteproc memory pointed by buf if success, otherwise NULL
	 */

```

**Comment by tammyleino** [comment]
@arnopo I guess I should do a PR first.

**Comment by tammyleino** [comment]
@arnopo The PR has completed - this can be closed.

**Comment by edmooring** [comment]
Closed per @tammyleino's request.
