### ISSUE TITLE
Virtqueues zeroed out twice

### ISSUE THREAD

**Issue by tammyleino** [OpenAMP/open-amp#353]
The rpmsg_init_vdev function fills virtqueues with zeros, but virtqueues are already initialized when memory is allocated for them in virtqueue_allocate. It seems the rpmsg_init_vdev function does not need to fill the structures again.

**Comment by arnopo** [comment]
Please could you give reference to the piece of code associated to "The rpmsg_init_vdev function fills virtqueues with zeros"?

**Comment by tammyleino** [comment]
@arnopo My mistake - this code is not in the codebase but is specific to ours.  Will close - thanks!
