### ISSUE TITLE
Error checking in API routines

### ISSUE THREAD

**Issue by tammyleino** [OpenAMP/open-amp#355]
As per discussion in RP call this week, I am going through the API routines to identify missing input parameter checks.  I have some questions about the following routines:

rpmsg_send_offchannel_raw / rpmsg_send_offchannel_nocopy - I think we should validate len for at least >= 0.  Should 0 bytes (an empty packet) be allowed to be sent; ie enforce > 0 requirement of len

rpmsg_virtio_init_shm_pool - Can a shared memory pool be initialized with a size of 0; ie, is there a way to configure the size later?

rpmsg_init_vdev - Confirming that shm_io is required input by master and remote.

This is a libmetal one, but I'll ask here just in case people have input; metal_io_init - Confirming that virt and physmap are required input by master and remote.

Thanks in advance!

**Comment by arnopo** [comment]
> As per discussion in RP call this week, I am going through the API routines to identify missing input parameter checks. I have some questions about the following routines:
> 
> rpmsg_send_offchannel_raw / rpmsg_send_offchannel_nocopy - I think we should validate len for at least >= 0. Should 0 bytes (an empty packet) be allowed to be sent; ie enforce > 0 requirement of len
> 
Right len should be tested in `rpmsg_send_offchannel_raw`. len == 0 for me is valid in OpenAMP and Linux implementation. I personally never tested this corner case, but I don't see any blocking point reviewing code. 

> rpmsg_virtio_init_shm_pool - Can a shared memory pool be initialized with a size of 0; ie, is there a way to configure the size later?

pool size is tested in rpmsg_init_vdev_with_config, but probably better to move test in rpmsg_virtio_init_shm_pool.

> rpmsg_init_vdev - Confirming that shm_io is required input by master and remote.

yes needed for both role

> 
> This is a libmetal one, but I'll ask here just in case people have input; metal_io_init - Confirming that virt and physmap are required input by master and remote.

Yes both need even if virt and physmap can be equal if no MMU

> 
> Thanks in advance!
