### ISSUE TITLE
Checking VIRTIO_CONFIG_STATUS_DRIVER_OK in remoteproc_create_virtio and rpmsg_init_vdev

### ISSUE THREAD

**Issue by tammyleino** [OpenAMP/open-amp#356]
I noticed that we check the status of the other side in both remoteproc_create_virtio and rpmsg_init_vdev.  I understand remoteproc_create_virtio waiting for the other side to be ready, but what could happen in the interim that rpmsg_init_vdev needs to check it again?

**Comment by arnopo** [comment]
Yes because rpmsg_init_vdev can be called with another virtio backend than the remoteproc virtio. In this case remoteproc_create_virtio is not called. It is the case in some [Zephyr examples](rpmsg_init_vdev).

**Comment by tammyleino** [comment]
Thank you @arnopo.
