### ISSUE TITLE
virtqueue_add_buffer returns error if vq->vq_free_cnt != 0

### ISSUE THREAD

**Issue by tammyleino** [OpenAMP/open-amp#358]
virtqueue_add_buffer has the following check:

```
VQ_PARAM_CHK(vq->vq_free_cnt == 0U, status, ERROR_VRING_FULL);
```

Since this function allows to add more than only one buffer, should the above check be implemented as this instead?

```
VQ_PARAM_CHK(vq->vq_free_cnt < needed, status, ERROR_VRING_FULL);
```

**Comment by arnopo** [comment]
Right,  Need to be fixed
Thank!
