### ISSUE TITLE
remoteproc_get_mem could match on wrong memory region name

### ISSUE THREAD

**Issue by tammyleino** [OpenAMP/open-amp#370]
The remoteproc_get_mem function compares names using the length of the given string (excluding "end-of-string" character) as a limit:
```
   if (name) {

      if (!strncmp(name, mem->name, strlen(name)))

         return mem;
```
As a result, it is possible to get a match when the given name is a subset of mem->name. For example, name of "shared" will match the mem->name "shared_memory".

Proposed code change:
```
			if ((strlen(name) == strlen(mem->name)) && (!strncmp(name, mem->name, RPROC_MAX_NAME_LEN)))
				return mem;
```

**Comment by arnopo** [comment]
`strncmp(name, mem->name, RPROC_MAX_NAME_LEN)` seems sufficient as `RPROC_MAX_NAME_LEN` is the max size of both strings.
The strncmp function will stop comparing if a null character is encountered in either in `name`  or `mem->name`.

**Comment by tammyleino** [comment]
mem = "shared"
mem->name = "shared_memory"

Without the strlen comparison, the code will incorrectly return a match, because it will encounter a null character in mem before getting to the end of mem->name

**Comment by arnopo** [comment]
I made a short test on my Linux PC
```
	char s1[20] = "shared_ram";
	char s2[10] = "shared";
	ret = strncmp(s1,s2, 6);
	LPRINTF("strncmp result1: %d\r\n", ret);
	ret = strncmp(s1,s2, 8);
	LPRINTF("strncmp result2: %d\r\n", ret);
```
the result is 
```
strncmp result1: 0
strncmp result2: 95
```
unless the behavior depends on the C library, it seems that the comparison using strncmp with RPROC_MAX_NAME_LEN size should detect the difference between the two strings.

**Comment by tammyleino** [comment]
@arnopo  I was concerned about C lib compatibility, which is why I proposed this solution, but after some experimentation with different compilers, I don't see a problem with excluding the strlen from the comparison.
