### ISSUE TITLE
Unused notification in rproc_virtio_set_status and rproc_virtio_set_features

### ISSUE THREAD

**Issue by tammyleino** [OpenAMP/open-amp#373]
These routines invoke the remoteproc notify operation as follows: 
```
rpvdev->notify(rpvdev->priv, vdev->notifyid);
```

But rproc_virtio_notified will return zero in the case that vdev->notifyid == notifyid, so this call will do nothing and can be removed.

**Comment by arnopo** [comment]
The notify with  vdev->notifyid is generally used by the host to kick the remote processor that virtio device has been updated.
For instance the Linux implementation send a notification when the vvdev status is set to DRIVER_OK.
The `rproc_virtio_notified` can be called by the host and the remote. In current OpenAMP remoteproc implementation the notification is ignored on remote side as you mentioned.
This probably could be improved in the future but the rpvdev->notify has to been kept as the use of `rproc_virtio_notified` is optional.
