### ISSUE TITLE
error while building with Yocto

### ISSUE THREAD

**Issue by yasetov** [OpenAMP/open-amp#38]
Hi,
I've just started to try OpenAMP. I've followed the instructions to install the open-amp and libmetal recipes with Yocto. However, I've got the following error:

"Nothing RPROVIDES 'rpmsg-examples' (but /home/yaset/QorIQ-SDK-V2.0-20160527-yocto/sources/meta-freescale/recipes-fsl/images/fsl-image-core.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'rpmsg-examples' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rpmsg-examples']"

I hope someone can help me with this.

Regards,

Yaset

**Comment by wjliang** [comment]
did you try https://github.com/openamp/meta-openamp?
The package name you specify will need to match the .bb file names
e.g. rpmsg-echo-test, rpmsg-mat-mul, rpmsg-proxy-app,  instead of the directory name which holds the .bb files
