### ISSUE TITLE
Interoperability Issues with nameservice feature support

### ISSUE THREAD

**Issue by tammyleino** [OpenAMP/open-amp#380]
I am testing with a Remote running 2021.04 and Host running 2018.10 OpenAMP.  The Host is not setting the nameservice bit in the gfeatures (even though it is configured in the resource table).  Looking through the code, I see where commit 11ebc42eaaf5ead2d73fba466e62e6525f8badbe from Jan 28, 2019 fixes a bug in rproc_virtio_set_features to set gfeatures instead of dfeatures and also adds the call to rproc_virtio_negotiate_features in rproc_virtio_create_vdev so the Host sets gfeatures for the Remote to read.  This code is not present in 2018.10, making 2018.10 incompatible with future versions of the nameservice negotiation code.  The side effect is that the Remote thinks the Host does not support nameservice announcements and therefore never sends them.

In discussing this on the OpenAMP RP call, it was suggested that the Remote could set RPMSG_IPU_C0_FEATURES in the gfeatures in the resource table when it is known that an older version of OpenAMP is being used on the Host. Even if the Host does not support nameservice announcements, they would be ignored when received.

**Comment by arnopo** [comment]
I don't see any way to know the remote version of OpenAMP, without adding extra code.
Yes, the workaround seems to populate the `gfeatures` in the resource table, with the same value as the `dfeatures`.
Have you tested it?

**Comment by tammyleino** [comment]
Yes, I tested and it is working when gfeatures of Remote is set in the resource table to match dfeatures to include nameservice support.

**Comment by arnopo** [comment]
So could we consider that the workaround for 2018.10 and previous versions is to force the gfeature in the resource table?
Or do you need that we create a v2018.04.1 to fix this ?

**Comment by tammyleino** [comment]
For my purposes, I am ok with the workaround.

**Comment by tammyleino** [comment]
@arnopo The workaround worked fine for me.  Should I close this issue?
