### ISSUE TITLE
what's plan to support the service/driver at the virtio level?

### ISSUE THREAD

**Issue by xiaoxiang781216** [OpenAMP/open-amp#390]
In Linux kernel, we can:

1. Write various virtio drivers(e.g. virtio-blk, virtio-net...)
2. Write various rpmsg drivers(e.g. rpmsg-char, rpmsg-tty...)

But, we can just write rpmsg drivers in Open-AMP, but virtio drivers is very useful in some case:

1. Interact with virito device/driver in Linux kernel(A core) from RTOS(M core) in the same SoC
2. Improve IPC performance in some(e.g. network or file system) case

So, I think the support of native virito driver is a great addition to Open-AMP, we(Xiaomi) are very interesting to improve Open-AMP virtio driver capability.

**Comment by arnopo** [comment]
Hello @xiaoxiang781216 ,

Some other companies are also interested in extending the open-amp library to support more Virtio services.
Some discussions and works are just starting on the topic. 
I added people involved as assignee of the issue.

**Comment by xiaoxiang781216** [comment]
Where can I find the related proposal or reference change? I want to evaluate the potential influence to the current code base. @arnopo @wmamills

**Comment by danmilea** [comment]
There's ongoing work to integrate a virtio MMIO front-end layer in the open-amp library based on the Zephyr virtio MMIO implementation from [https://github.com/danmilea/zephyr/blob/main/drivers/virtio/virtio-mmio.c](url) (updated to use OpenAMP virtqueue APIs), with the goal to also include support for device drivers (e.g. virtio console, virtio-net).

The framework will also support hypervisorless mode operation. More information on hypervisorless virtio is available here: 
- [https://www.openampproject.org/news/hypervisorless-virtio-blog/](url)
- [https://github.com/danmilea/hypervisorless_virtio_zcu102](url)

@xiaoxiang781216

**Comment by xiaoxiang781216** [comment]
Thanks @danmilea . I will study these document and feedback to you soon.

**Comment by xiaoxiang781216** [comment]
@danmilea @arnopo I see that all virito driver support is done on virtio-exp branch, when will the work merge back to the main branch?

**Comment by xiaoxiang781216** [comment]
@danmilea will you continue MMIO transport in the near feature?

**Comment by danmilea** [comment]
@xiaoxiang781216 Do you mean adding support for the remoteproc style of virtio? Before looking into that, I think it's more relevant to investigate the requirements of an OpenAMP-based solution for VIRTIO back-ends, since the current implementation includes only front-end support. The scope pf my current work is to get everything on a usable level in a hypervisorless-virtio type of deployment.

**Comment by CV-Bowen** [comment]
> There's ongoing work to integrate a virtio MMIO front-end layer in the open-amp library based on the Zephyr virtio MMIO implementation from [https://github.com/danmilea/zephyr/blob/main/drivers/virtio/virtio-mmio.c](url) (updated to use OpenAMP virtqueue APIs), with the goal to also include support for device drivers (e.g. virtio console, virtio-net).
> 
> The framework will also support hypervisorless mode operation. More information on hypervisorless virtio is available here:
> 
> * [https://www.openampproject.org/news/hypervisorless-virtio-blog/](url)
> * [https://github.com/danmilea/hypervisorless_virtio_zcu102](url)
> 
> @xiaoxiang781216

@danmilea Hi, I want to implement the virtio-mmio-serial/net driver based on openamp. Do you have some examples show how to use the virtio mmio apis in virito-exp branch?

**Comment by danmilea** [comment]
Hi @CV-Bowen 
[zephyr-openamp-staging](https://github.com/OpenAMP/zephyr-openamp-staging) (branch virtio-exp) includes [samples](https://github.com/OpenAMP/zephyr-openamp-staging/tree/virtio-exp/samples/virtio) for net and serial which use the open-amp library virtio mmio support in a standard virtual guest configuration. The hvl_net_rng_reloc sample works in a hypervisorless virtio environment (details in the sample [README.rst](https://github.com/OpenAMP/zephyr-openamp-staging/tree/virtio-exp/samples/virtio/hvl_net_rng_reloc#readme) file).

**Comment by CV-Bowen** [comment]
@danmilea Got, Thanks a lot.

**Comment by arnopo** [comment]
@CV-Bowen , @danmilea, @xiaoxiang781216, 

We have 2 complementary PRs for Virtio. I'd like to suggest that we move forward step by step to have a common dev approved  by everyone and ease the reviews by splitting PRs.

step 1:
- [ ] @CV-Bowen : create a new PR that introduce virtio API with create_virtqueues/delete_virtqueues dispatcher ops
      => no remorteproc_virtio or rpmsg update that will come in step 3

step 2:
- [ ] @danmilea : create a new PR with virtio MMIO transport only that use new dispatcher ops

step3
- [ ] @CV-Bowen  update #489( or create new one )   for the remoteproc virtio implementation and virtio RPMsg
- [ ] @danmilea: update #494 ( or create new one) for virtio services

**Comment by arnopo** [comment]
Step 1 merged :  https://github.com/OpenAMP/open-amp/pull/495
