### ISSUE TITLE
handle_rsc_table() can process garbage resource entries

### ISSUE THREAD

**Issue by edmooring** [OpenAMP/open-amp#393]
It looks like if there is a resource with a type between RSC_LAST and RSC_VENDOR_START, or > RSC_VENDOR_LAST, it will just be skipped in handle_rsc_table(). I'm pretty sure this isn't what we want to do.

**Comment by arnopo** [comment]
Hi @edmooring 
could you detail what you have in mind?
Definition are aligned with Linux ones(https://elixir.bootlin.com/linux/v5.18-rc1/source/include/linux/remoteproc.h#L116). Values between RSC_LAST and RSC-VENDOR are reserved for future usage, I guess.
