### ISSUE TITLE
cannot find -lzip/-lfdt

### ISSUE THREAD

**Issue by mhrztrk** [OpenAMP/open-amp#4]
When i execute command 'source open_amp_build.sh', i am getting an about missing libraries. Do we need to compile these libraries (fdt,zlib) seperately and add to project? 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Building Linux Bootstrap
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CC libs/system/zc702evk/linux/boot.o
CC libs/system/zc702evk/linux/rsc_table.o
AS libs/system/zc702evk/linux/boot_wrapper.o
Building linux aggregate image : libs/system/zc702evk/linux/firmware
arm-xilinx-eabi-gcc  -nostartfiles -T"/home/mhrztrk/RFI/work/open-amp/libs/system/zc702evk/linux/link_remote.ld" -L"/home/mhrztrk/RFI/work/open-amp/libs/system/zc702evk/linux/lib/arm-xilinx-eabi-"  -o "libs/system/zc702evk/linux/firmware" -Wl,--start-group  libs/system/zc702evk/linux/boot.o  libs/system/zc702evk/linux/rsc_table.o  libs/system/zc702evk/linux/boot_wrapper.o -lc -lm -lstdc++ -lzlib -lfdt -Wl,--end-group 	
/opt/Xilinx/petalinux-v2014.4-final/tools/linux-i386/arm-xilinx-gnueabi/bin/../lib/gcc/arm-xilinx-eabi/4.8.3/../../../../arm-xilinx-eabi/bin/ld: cannot find -lzlib
/opt/Xilinx/petalinux-v2014.4-final/tools/linux-i386/arm-xilinx-gnueabi/bin/../lib/gcc/arm-xilinx-eabi/4.8.3/../../../../arm-xilinx-eabi/bin/ld: cannot find -lfdt
collect2: error: ld returned 1 exit status
make: *** [libs/system/zc702evk/linux/firmware] Error 1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by wjliang** [comment]
the libs are removed from earlier, they are added back in the latest version.

however, since they are *.a files, they are supposed to be removed later and add one more step to build them. Will make this change later
