### ISSUE TITLE
Possible corruption of lists in remoteproc_add_mem and remoteproc_init by adding same member twice

### ISSUE THREAD

**Issue by tammyleino** [OpenAMP/open-amp#400]
Instances remoteproc and remoteproc_mem can be added to the lists with the appropriate instances even though they are already on them. Before any instance is added to the list, a check should be made to see if it is already on this list.

Such cases occur in the remoteproc_add_mem and remoteproc_init functions.

If the same object is added to the list twice, it will disturb the whole order and it will not be possible to go through the whole list correctly.

**Comment by arnopo** [comment]
yes 
A check could be added at the begining of in remoteproc_create_virtio and  in remoteproc_add_mem
