### ISSUE TITLE
hil_set_shm(): incorrect test of memory size?

### ISSUE THREAD

**Issue by rfeneon** [OpenAMP/open-amp#41]
Hi, in hil_set_shm() at line 660 it seems the test for valid memory size is not correct:

if (proc->sh_buff.io) {
  io = proc->sh_buff.io;
    if (io->size > size)
      return -1;
...

I think it should be:
    if (io->size < size)
      return -1;

Thanks

**Comment by wjliang** [comment]
Thanks for pointer out the issue, and yes, it needs to change that way.

**Comment by wjliang** [comment]
Fix is in the commit: ecb25fb3abb7620cb8c0ca640ff51dfae66aa94b
