### ISSUE TITLE
bare metal application debugging with Xilinx XSDK not working

### ISSUE THREAD

**Issue by sportfloh** [OpenAMP/open-amp#42]
The problem I'm having is described in this Xilinx forum thread:
https://forums.xilinx.com/t5/OpenAMP/How-to-debug-PS1-with-SDK-Config-PS0-Petalinux-PS1-Baremetal/td-p/810314

Is there any solution for this problem?

**Comment by wjliang** [comment]
You can set breakpoint on core1 before you load the application directly from xsdb to debug the issue. For XSDK question, please use https://www.xilinx.com/support.html#serviceportal to raise the issue/question.

Thanks,
Wendy
