### ISSUE TITLE
Continuous integration failure for all OA PRs

### ISSUE THREAD

**Issue by danmilea** [OpenAMP/open-amp#450]
The OpenAMP continuous integration check triggered by new OA pull requests fails because the Zephyr openamp sample in samples/subsys/ipc/openamp/ fails to build for board lpcxpresso54114_m4. 

The failure is triggered by the "west build -b lpcxpresso54114_m4 samples/subsys/ipc/openamp/ || exit 1" command in build_zephyr() in .github/actions/build_ci/entrypoint.sh.

The failure can be reproduced by building the subsys/ipc/openamp/ sample in a standard Zephyr environment based on the latest upstream version.
commit 23f057804285c26806863daed1d095dd06ebc2dc (HEAD -> main, origin/main, origin/HEAD)
Author: Anas Nashif <anas.nashif@intel.com>
Date:   Sun Nov 20 07:02:41 2022 -0500

Until the issue is fixed in upstream Zephyr, could this check be either disabled or replaced with a valid one?

[build_21112022.log](https://github.com/OpenAMP/open-amp/files/10057288/build_21112022.log)

**Comment by arnopo** [comment]
also cherry picked in `virtio-exp` branch
