### ISSUE TITLE
Build failure - Ubuntu 22.10 / gcc-12

### ISSUE THREAD

**Issue by danmilea** [OpenAMP/open-amp#455]
Build open-amp for Linux as described in build_linux in
https://github.com/OpenAMP/open-amp/blob/main/.github/actions/build_ci/entrypoint.sh 

On Ubuntu 22.10 with default compiler gcc-12 the compilation will fail.
[build_failure_gcc12_ubuntu22.10.txt](https://github.com/OpenAMP/open-amp/files/10119563/build_failure_gcc12_ubuntu22.10.txt)

**Comment by sergeyblagodarnyy** [comment]
Try to remove `-Werror` compiling option.
