### ISSUE TITLE
Resolve build warnings with Doxygen generation

### ISSUE THREAD

**Issue by tammyleino** [OpenAMP/open-amp#458]
Documentation generation is OFF by default due to build warnings with doxygen.  These warnings should be examined to determine if there is a viable resolution so documentation generation can be enabled by default.

Related PR - https://github.com/OpenAMP/open-amp/pull/452

**Comment by arnopo** [comment]
@tammyleino  
could you confirm that you don't see any warning on code generation after integrating #597 ?
