### ISSUE TITLE
License

### ISSUE THREAD

**Issue by arj** [OpenAMP/open-amp#462]
It is unclear to me under which license open-amp is published.
In the license file I see 4 different licenses listed (BSD3, BSD2, Apache, GPL)

Could you please clarify what the license of open-amp is?
Thanks!

**Comment by arnopo** [comment]
It is a good point. It is not clearly mentioned and we have to improve this.

- The libmetal and open-amp libraries are published under BSD 2/3 license
- The associated CI test scripts are also inherit from the GPL and Apache license

**Comment by arj** [comment]
Thank you for this clarification!
