### ISSUE TITLE
Question about the resource table

### ISSUE THREAD

**Issue by shellyfengfeng** [OpenAMP/open-amp#487]
Resource table seems defined by remote, why not the master define the related resouce such as shared memory and vring address?
Thanks.

**Comment by shellyfengfeng** [comment]
Thanks for your reply. But It seems the section ".resource_table" is used in the remote to tell the master the vring and share memory information. 发自我的手机-------- 原始邮件 --------发件人： Tanmay ***@***.***>日期： 2023年5月9日周二 晚上10:33收件人： OpenAMP/open-amp ***@***.***>抄送： shellyfengfeng ***@***.***>, Author ***@***.***>主    题： Re: [OpenAMP/open-amp] Question about the resource table (Issue #487)
I am assuming master is linux kernel. In that case, remoteproc node in device-tree contains "memory-region" property which has vring addresses.

**Comment by arnopo** [comment]
@shellyfengfeng 
Please could you resent a readable comment

**Comment by shellyfengfeng** [comment]
I mean master will load the remote image and get resource table from the remote image.
If the master has such definition, the master doesn't need to load the resource table from the remote image.

**Comment by edmooring** [comment]
The remote side contains configuration information about things like how many virtio devices are expected that the host side has no way of obtaining other than by reading the resource table. The Linux kernel can and does also write to the resource table to inform the remote side of such things as shared memory addresses.

**Comment by shellyfengfeng** [comment]
> The remote side contains configuration information about things like how many virtio devices are expected that the host side has no way of obtaining other than by reading the resource table. The Linux kernel can and does also write to the resource table to inform the remote side of such things as shared memory addresses.

Assuming the host and the remote are baremental, after the host load the remote image, it will load the ".resource_table" seciton and  use the "rsc_table" to initial the vring and virtqueues.

**Comment by arnopo** [comment]
@shellyfengfeng 
Are you waiting for more information or can we close the issue?

**Comment by shellyfengfeng** [comment]
Yes, please close the issue.
