### ISSUE TITLE
OpenAMP Linux to Linux

### ISSUE THREAD

**Issue by duanem** [OpenAMP/open-amp#86]
I'd like to be able to test and develop my OpenAMP functionality without access to hardware (or emulator) for the target system. Is it possible to use the OpenAMP APIs to communicate within the same Linux OS?

For example use `remoteproc` to load a process using OpenAMP back into the same OS?

Other suggestions for testing are welcome.

**Comment by wjliang** [comment]
in the README.md, there is a section "Example to compile OpenAMP for communication between Linux processes", you can start from there.

**Comment by duanem** [comment]
I should have paid more attention to the readme! Thank you!
