### ISSUE TITLE
Add support for zero copy send & receive

### ISSUE THREAD

**Issue by galak** [OpenAMP/open-amp#97]
The new decoupling work dropped support for zero copy support that was added in commit b16ca550f1d5734692d5204d148a1ed2ffb680c7. This needs to get added back, but needs discussion in OpenAMP group.

**Comment by xiaoxiang781216** [comment]
@galak and @wjliang,
When zero copy will get back? We plan to integrate to the latest master branch, but our platform utilize zero copy heavily,
